version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  migrate:
    build: .
    command: flask db upgrade
    depends_on:
      - db
    networks:
      - app_network
    environment:
      FLASK_APP: app.py
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}

  flask_app:
    build: .
    command: /bin/sh -c "while ! nc -z db 5432; do sleep 1; done; python run.py"
    environment:
      APP_PORT: 80
      FLASK_APP: app.py
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
    depends_on:
      - db
      - migrate
    networks:
      - app_network
    volumes:
      - .:/usr/src/app

  react_app:
    build:
      context: .
      dockerfile: ${REACT_DOCKER_FILE}  # Specify the development Dockerfile here
    environment:
      - HOST=${REACT_HOST:-}
      - DANGEROUSLY_DISABLE_HOST_CHECK=${DANGEROUSLY_DISABLE_HOST_CHECK:-false}
    networks:
      - app_network
    volumes:
      - .:/app  # Ensure this is the path to your React source code
      - /app/node_modules  # Use a volume to persist node_modules

  ngrok:
    image: wernight/ngrok
    depends_on:
      - nginx
    ports:
      - "4040:4040"
    command: ngrok http nginx:80
    environment:
      NGROK_AUTHTOKEN: ${NGROK_TOKEN}
    networks:
      - app_network
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose Nginx on port 80 of the host
    depends_on:
      - flask_app
      - react_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom Nginx config
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
