version: '3.8'
services:
  flask_app:
    build: .
    environment:
      - APP_PORT=80
    ports:
      - "5000:80"  # Corrected port mapping
    networks:
      - app_network

  react_app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    networks:
      - app_network

  ngrok:
    image: wernight/ngrok
    depends_on:
      - flask_app
    ports:
      - "4040:4040"
    command: ngrok http flask_app:80
    environment:
      NGROK_AUTHTOKEN: 2d1W8gjaXvmU3M2Bmrd8HQOrwQr_33yaPDJqxrQyNNpA8w9kD
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
