version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      POSTGRES_DB: onepagerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  migrate:
    build: .
    command: flask db upgrade
    depends_on:
      - db
    networks:
      - app_network
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/onepagerdb

  flask_app:
    build: .
    command: /bin/sh -c "while ! nc -z db 5432; do sleep 1; done; python run.py"
    environment:
      APP_PORT: 80
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/onepagerdb
    ports:
      - "5000:80"
    depends_on:
      - db
      - migrate
    networks:
      - app_network
    volumes:
      - .:/usr/src/app

  react_app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    networks:
      - app_network

  ngrok:
    image: wernight/ngrok
    depends_on:
      - flask_app
    ports:
      - "4040:4040"
    command: ngrok http flask_app:80
    environment:
      NGROK_AUTHTOKEN: 2d1W8gjaXvmU3M2Bmrd8HQOrwQr_33yaPDJqxrQyNNpA8w9kD
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
