"""initial migration

Revision ID: 290fbcf04d8a
Revises: 
Create Date: 2024-03-31 00:49:54.075709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290fbcf04d8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.String(length=64), nullable=True),
    sa.Column('imageResourceUrl', sa.String(length=256), nullable=True),
    sa.Column('storeName', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_productName'), ['productName'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_productName'))

    op.drop_table('product')
    # ### end Alembic commands ###
