name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the workspace
      run: ls -la

    - name: Import GPG Key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import --no-tty --pinentry-mode loopback

    - name: Decrypt .env.prod.secret
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "${GPG_PASSPHRASE}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --decrypt --output .env.prod .env.prod.secret
        if [ ! -f .env.prod ]; then
          echo ".env.prod file not created, decryption failed."
          exit 1
        fi

    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: '45.76.61.43'
        username: onepageruser
        password: Khareghush1369
        port: 22
        source: "./"
        target: /home/onepageruser


    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/onepager
          docker-compose down
          docker-compose up --env-file .env.prod --build -d
